//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AM_The_Tea_Round_Picker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tea
    {
        public int TeaId { get; set; }
        public string TeaName { get; set; }
    }
}
